services:
  valkey:
    image: valkey/valkey:8
    container_name: arf-valkey
    ports:
      - "6379:6379"
    volumes:
      - valkey-data:/data

  mongodb:
    image: mongo:7
    container_name: arf-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  valkey-data:
  mongo-data:
